### ISSUE TITLE
How to use decals that are made ready for Decal machine with the Slap it Plugin? 

### ISSUE THREAD

**Issue by YHSX88** [artempoletsky/blender_slap_it#1]
Hi I'm seeing a lot of the decals on the marketplaces are ready for this Decal machine plugin.

Can I safely use them with Slap it Plugin ? 
if not what steps are needed ? 

Example: https://blendermarket.com/products/50-sci-fi-decals-pack-with-bounce-light-decalmachine-2

Thanks !

**Comment by artempoletsky** [comment]
Hi. 
If theese decals are images you can use them. If you want them to have emission and normal maps you can watch tutorials on youtube how to make materials in Blender.
